Version checks for boolean properties
devfile/library pull request #126
Opened 2021-12-02 18:58 UTC by kim-tsao

### What does this PR do?:

Adds a version check when setting defaults for the ephemeral property

### Which issue(s) this PR fixes:

https://github.com/devfile/api/issues/697

### PR acceptance criteria:
Testing and documentation do not need to be complete in order for this PR to be approved. We just need to ensure tracking issues are opened.

> - Open new test/doc issues under the [devfile/api](https://github.com/devfile/api/issues) repo
> - Check each criteria if:
>  - There is a separate tracking issue. Add the issue link under the criteria
>  **or**
>  - test/doc updates are made as part of this PR
> -  If unchecked, explain why it's not needed

- [ ] Unit/Functional tests

  

- [ ] [QE Integration test](https://github.com/devfile/integration-tests) 

  

- [ ] Documentation 

   

- [ ] Client Impact

  

### How to test changes / Special notes to the reviewer:
build a new odo binary and run the scenario detailed in https://github.com/devfile/api/issues/697

2021-12-03 08:10 UTC, feloy commented
This patch fixes the issue raised in #697. Thanks @kim-tsao

2021-12-06 15:17 UTC, yangcao77 requested changes
thanks for the change Kim. besides the comment I put below, can you also add unit tests for `setDefaults()` and  the new function,`verifyEphemeralUnset()`, introduced by this PR?
we want to have new functions also covered by unit tests

2021-12-06 15:17 UTC, yangcao77 commented on pkg/devfile/parser/parse.go
> +	schemaVersion := d.Data.GetSchemaVersion()
`DevfileObj.Ctx.GetApiVersion()` should take higher priority than `Data.GetSchemaVersion()`. 

```
	if devfileVersion = DevfileObj.Ctx.GetApiVersion(); devfileVersion == "" {
		devfileVersion = DevfileObj.Data.GetSchemaVersion()
	}
```

2021-12-07 00:50 UTC, kim-tsao commented
> thanks for the change Kim. besides the comment I put below, can you also add unit tests for `setDefaults()` and the new function,`verifyEphemeralUnset()`, introduced by this PR? we want to have new functions also covered by unit tests

`verifyEphemeralUnset()` is just a new function in our test utils.  I added unit tests for `setDefaults()` - it was a worthwhile effort since I found and fixed a bug related to setting defaults on `dedicatedPod` and `mountSources`.  I also cleaned up some error handling that was missed.

2021-12-07 20:40 UTC, yangcao77 approved these changes
Changes lgtm

2021-12-07 20:52 UTC, merged